apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
      - name: survey-app
        image: yashdayma55/survey-app:latest  
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:////app/db.sqlite3"
        volumeMounts:
        - name: db-storage
          mountPath: /app/db.sqlite3
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: survey-db-pvc